// domains.js or config file
export const domainTopicsMap = {
  "Web Development": {
    topics: [
      "web-development",
      "frontend-development",
      "fullstack-development",
      "web-app",
      "web-framework",
      "react",
      "nextjs",
      "vue",
      "nodejs",
      "express",
      "spa",
      "pwa",
      "tailwindcss",
      "redux",
      "web-performance",
    ],
  },

  "DevOps & Cloud": {
    topics: [
      "devops",
      "cloud-computing",
      "infrastructure-as-code",
      "ci-cd",
      "containers",
      "docker",
      "kubernetes",
      "terraform",
      "ansible",
      "jenkins",
      "aws",
      "gcp",
      "azure",
      "monitoring",
      "gitops",
    ],
  },

  "Machine Learning & AI": {
    topics: [
      "machine-learning",
      "deep-learning",
      "neural-networks",
      "ai",
      "artificial-intelligence",
      "pytorch",
      "tensorflow",
      "computer-vision",
      "nlp",
      "llm",
      "transformers",
      "model-training",
      "reinforcement-learning",
      "generative-ai",
      "mlops",
    ],
  },

  "Blockchain & Web3": {
    topics: [
      "blockchain",
      "ethereum",
      "solidity",
      "web3",
      "smart-contracts",
      "dapp",
      "defi",
      "nft",
      "cryptocurrency",
      "wallet",
      "hardhat",
      "truffle",
      "metamask",
      "cryptography",
      "web3js",
    ],
  },

  "Systems Programming": {
    topics: [
      "systems-programming",
      "os-development",
      "kernel-development",
      "system-architecture",
      "embedded-systems",
      "compilers",
      "concurrency",
      "networking",
      "low-level",
      "unix",
      "device-drivers",
      "memory-management",
      "distributed-systems",
      "parallel-computing",
      "performance-optimization",
    ],
  },

  "Mobile Development": {
    topics: [
      "mobile-development",
      "android-app",
      "ios-app",
      "mobile-ui",
      "mobile-framework",
      "react-native",
      "flutter",
      "jetpack-compose",
      "swiftui",
      "cross-platform",
      "mobile-design",
      "mobile-backend",
      "app-deployment",
      "mobile-security",
      "hybrid-app",
    ],
  },

  Cybersecurity: {
    topics: [
      "cybersecurity",
      "ethical-hacking",
      "penetration-testing",
      "vulnerability-assessment",
      "infosec",
      "pentesting",
      "osint",
      "malware-analysis",
      "reverse-engineering",
      "bug-bounty",
      "ctf",
      "security-audit",
      "kali-linux",
      "network-security",
      "threat-hunting",
    ],
  },

  "Game Development": {
    topics: [
      "game-development",
      "gamedev",
      "game-design",
      "unity",
      "unreal-engine",
      "godot",
      "game-engine",
      "multiplayer-game",
      "shader-programming",
      "gamephysics",
      "2d-game",
      "3d-game",
      "level-design",
      "asset-creation",
      "ue5",
    ],
  },

  "Data Science & Analytics": {
    topics: [
      "data-science",
      "data-analysis",
      "data-engineering",
      "data-visualization",
      "big-data",
      "analytics",
      "statistics",
      "dataset",
      "etl",
      "jupyter-notebook",
      "data-cleaning",
      "feature-engineering",
      "business-intelligence",
      "exploratory-data-analysis",
      "data-pipeline",
    ],
  },

  "IoT & Embedded": {
    topics: [
      "iot",
      "internet-of-things",
      "arduino",
      "raspberry-pi",
      "esp32",
      "esp8266",
      "embedded-systems",
      "microcontroller",
      "firmware",
      "sensors",
      "mqtt",
      "robotics",
      "home-automation",
      "edge-computing",
      "hardware",
    ],
  },

  "Backend & Databases": {
    topics: [
      "backend-development",
      "server-side",
      "api-design",
      "rest-api",
      "graphql",
      "microservices",
      "scalability",
      "database",
      "postgresql",
      "mongodb",
      "mysql",
      "caching",
      "redis",
      "authentication",
      "system-design",
    ],
  },

  "Cloud Native": {
    topics: [
      "cloud-native",
      "kubernetes",
      "docker",
      "service-mesh",
      "serverless",
      "distributed-systems",
      "microservices",
      "containerization",
      "istio",
      "grpc",
      "observability",
      "monitoring",
      "scalability",
      "orchestration",
      "cloud-architecture",
    ],
  },
};
