// domains.js or config file
export const domainTopicsMap = {
  "Web Development": {
    topics: [
      "javascript",
      "react",
      "vue",
      "angular",
      "nextjs",
      "nodejs",
      "express",
      "graphql",
      "rest-api",
      "typescript",
      "frontend",
      "fullstack",
    ],
  },

  "DevOps & Cloud": {
    topics: [
      "docker",
      "kubernetes",
      "terraform",
      "ansible",
      "jenkins",
      "cicd",
      "aws",
      "azure",
      "gcp",
      "observability",
      "prometheus",
      "grafana",
    ],
  },

  "Machine Learning & AI": {
    topics: [
      "machine-learning",
      "deep-learning",
      "tensorflow",
      "pytorch",
      "neural-networks",
      "computer-vision",
      "nlp",
      "reinforcement-learning",
      "scikit-learn",
      "keras",
      "transformers",
      "llm",
    ],
  },

  "Blockchain & Web3": {
    topics: [
      "blockchain",
      "ethereum",
      "bitcoin",
      "smart-contracts",
      "solidity",
      "web3",
      "defi",
      "nft",
      "dapp",
      "cryptography",
      "polygon",
      "zk",
    ],
  },

  "Systems Programming": {
    topics: [
      "operating-systems",
      "osdev",
      "kernel",
      "compilers",
      "assembly",
      "embedded",
      "firmware",
      "concurrency",
      "networking",
      "linux",
      "virtualization",
      "profiling",
    ],
  },

  "Mobile Development": {
    topics: [
      "android",
      "ios",
      "react-native",
      "flutter",
      "kotlin",
      "swift",
      "mobile-app",
      "jetpack-compose",
      "swiftui",
      "cross-platform",
      "expo",
      "pwa",
    ],
  },

  Cybersecurity: {
    topics: [
      "security",
      "cybersecurity",
      "infosec",
      "ethical-hacking",
      "penetration-testing",
      "vulnerabilities",
      "malware",
      "reverse-engineering",
      "web-security",
      "owasp",
      "forensics",
      "ctf",
    ],
  },

  "Game Development": {
    topics: [
      "gamedev",
      "game-development",
      "unity",
      "unreal-engine",
      "godot",
      "game-engine",
      "3d",
      "2d",
      "graphics",
      "shader",
      "multiplayer",
      "opengl",
    ],
  },

  "Data Science & Analytics": {
    topics: [
      "data-science",
      "data-analysis",
      "data-visualization",
      "pandas",
      "numpy",
      "jupyter",
      "big-data",
      "analytics",
      "statistics",
      "data-engineering",
      "etl",
      "spark",
    ],
  },

  "IoT & Embedded": {
    topics: [
      "iot",
      "embedded",
      "arduino",
      "raspberry-pi",
      "esp32",
      "mqtt",
      "sensors",
      "firmware",
      "hardware",
      "robotics",
      "microcontroller",
      "rtos",
    ],
  },

  "Backend & Databases": {
    topics: [
      "backend",
      "api",
      "rest-api",
      "graphql",
      "database",
      "postgresql",
      "mongodb",
      "mysql",
      "redis",
      "authentication",
      "orm",
      "caching",
    ],
  },

  "Cloud Native": {
    topics: [
      "cloud-native",
      "kubernetes",
      "docker",
      "service-mesh",
      "istio",
      "containers",
      "helm",
      "distributed-systems",
      "grpc",
      "observability",
      "k8s",
      "service-discovery",
    ],
  },
};
